# Generated by Django 4.1.5 on 2023-01-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone',
            new_name='mobile',
        ),
    ]
